# Generated by Django 2.0.4 on 2018-05-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20180502_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
    ]
