# Generated by Django 2.0.4 on 2018-05-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20180502_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_v1.Group'),
        ),
    ]
