# Generated by Django 2.0.4 on 2018-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_auto_20180502_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
