# Generated by Django 2.0.4 on 2018-05-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='csr',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_v1.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
