# Generated by Django 2.0.4 on 2018-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_certificate_revoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='csr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
