# Generated by Django 2.0.4 on 2018-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_certificate_basename'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='serial',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
