# Generated by Django 2.0.4 on 2018-05-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_certificate_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
