# Generated by Django 2.0.4 on 2018-05-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_auto_20180503_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='wR1ntbWWFYQyv2hX', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='s8jYbYMyZONT', max_length=30, unique=True),
        ),
    ]
