# Generated by Django 2.0.4 on 2018-05-04 13:00

from django.db import migrations, models
import openvpn_restapi.api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_auto_20180504_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=openvpn_restapi.api_v1.models.get_random_string_model, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=openvpn_restapi.api_v1.models.get_random_string_model, max_length=30, unique=True),
        ),
    ]
